### ISSUE TITLE
Good work. Also see...

### ISSUE THREAD

**Issue by KarlHegbloom** [slowphil/texmacs-win-builder#1]
https://github.com/KarlHegbloom/zotero-texmacs-integration

Use the wip-performance-improvements branch... can you please test and maybe fix it to make it work on Windows?

Please also test my installation instructions.

I might make the propaci-texmacs perform or ensure a git clone install of zotero-texmacs-integration.

This code is alpha! Please try to write a research essay, ok?

**Comment by slowphil** [comment]
I'm sure it is pretty useful for writing legal document, but sorry Karl, this is not my party and  I see nothing there that would be really useful for writing scientific papers or that I feel a need for. Moreover, as I already mentioned to you, I dislike the idea of introducing new tags that de facto make this incompatible with standard TeXmacs. Thus, I really lack motivation for spending time installing it and learning how to use it.
