### ISSUE TITLE
exe generation issue

### ISSUE THREAD

**Issue by Yibbou** [slowphil/texmacs-win-builder#4]
Hi all,
I tried to generate "texmacs.exe" using the last version of "texmacs win builder" (I use windows10 - 64b)

After 45 minutes of processing, I get the message (in french): 
"ERREUR : Une erreur s’est produite dans prepare().
    Abandon…
**********************************************************
*                                                        *
*      The TeXmacs installer was not created...          *
*                                                        *
*            something went wrong :(                     *
**********************************************************
"

This detail of the process is as follows:
"
résolution des dépendances…
recherche des conflits entre paquets…

Paquets (1) mingw-w64-i686-poppler-qt4-0.45.0-1

Taille totale installée :    14.88 MiB
Taille de mise à jour nette :   0.00 MiB

:: Procéder à l’installation ? [O/n]
(1/1) vérification des clés dans le trousseau      [#####################] 100%
(1/1) vérification de l’intégrité des paquets      [#####################] 100%
(1/1) chargement des fichiers des paquets          [#####################] 100%
(1/1) analyse des conflits entre fichiers          [#####################] 100%
(1/1) vérification de l’espace disque disponible   [#####################] 100%
:: Traitement des changements du paquet…
(1/1) réinstallation mingw-w64-i686-poppler-qt4    [#####################] 100%
==> ATTENTION : Un paquet a déjà été compilé, installation du paquet existant…
==> Installation du paquet mingw-w64-i686-wget avec pacman -U…
chargement des paquets…
avertissement : mingw-w64-i686-wget-1.20.3-1 est à jour -- réinstallation
résolution des dépendances…
recherche des conflits entre paquets…

Paquets (1) mingw-w64-i686-wget-1.20.3-1

Taille totale installée :    3.12 MiB
Taille de mise à jour nette :  0.00 MiB

:: Procéder à l’installation ? [O/n]
(1/1) vérification des clés dans le trousseau      [#####################] 100%
(1/1) vérification de l’intégrité des paquets      [#####################] 100%
(1/1) chargement des fichiers des paquets          [#####################] 100%
(1/1) analyse des conflits entre fichiers          [#####################] 100%
(1/1) vérification de l’espace disque disponible   [#####################] 100%
:: Traitement des changements du paquet…
(1/1) réinstallation mingw-w64-i686-wget           [#####################] 100%
==> Création du paquet mingw-w64-texmacs r1-1 (dim. 12 mai 2019 12:55:06)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> Mise à jour du dépôt texmacs svn
Mise à jour de '.' :
À la révision 11651.
==> Validation des fichiers source avec sha1sums…
    texmacs ... Ignoré
==> Extraction des sources…
  -> Création d’une copie de travail du dépot src svn…
==> Lancement de prepare()…
svn11651+extras
patching file TeXmacs/doc/about/about-summary.de.tm
patching file TeXmacs/doc/about/about-summary.en.tm
Hunk #1 succeeded at 7 with fuzz 2.
patching file TeXmacs/doc/about/about-summary.es.tm
patching file TeXmacs/doc/about/about-summary.fr.tm
patching file TeXmacs/doc/about/about-summary.it.tm
patching file TeXmacs/doc/about/about-summary.zh.tm
patching file misc/m4/tm_subversion.m4
patching file packages/windows/TeXmacs.iss.in
patching file packages/windows/resource.rc.in
Hunk #1 succeeded at 31 with fuzz 1.
patching file TeXmacs/doc/devel/scheme/api/glue-auto-doc.en.tm
patching file TeXmacs/progs/prog/glue-symbols.scm
patching file TeXmacs/progs/utils/misc/updater.scm
patching file src/Plugins/Updater/tm_updater.cpp
patching file src/Plugins/Updater/tm_updater.hpp
patching file src/Plugins/Updater/tm_winsparkle.cpp
patching file src/Plugins/Updater/tm_winsparkle.hpp
patching file src/Scheme/Glue/build-glue-basic.scm
patching file src/Scheme/Glue/glue_basic.cpp
Hunk #2 succeeded at 9819 (offset 346 lines).
patching file TeXmacs/doc/main/convert/man-convert.en.tm
patching file TeXmacs/doc/main/convert/man-equation-editor.en.tm
patching file TeXmacs/doc/main/convert/man-graphics-export.en.tm
patching file TeXmacs/misc/inkscape_extension/texmacs_reedit.py
patching file TeXmacs/progs/convert/images/tmimage.scm
patching file TeXmacs/progs/init-texmacs.scm
Hunk #1 succeeded at 342 (offset 11 lines).
patching file TeXmacs/progs/texmacs/menus/preferences-widgets.scm
patching file plugins/equation-editor/progs/init-equation-editor.scm
patching file src/System/Boot/init_texmacs.cpp
Hunk #1 succeeded at 368 (offset 1 line).
Hunk #2 succeeded at 423 (offset 1 line).
patching file misc/m4/tm_platform.m4
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file misc/m4/tm_platform.m4.rej
patching file src/Data/String/converter.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/Data/String/converter.cpp.rej
patching file src/Data/String/converter.hpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/Data/String/converter.hpp.rej
patching file src/Edit/Modify/edit_text.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/Edit/Modify/edit_text.cpp.rej
patching file src/Plugins/Pdf/pdf_hummus_renderer.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
4 out of 4 hunks ignored -- saving rejects to file src/Plugins/Pdf/pdf_hummus_renderer.cpp.rej
patching file src/Plugins/Qt/QTMFileDialog.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file src/Plugins/Qt/QTMFileDialog.cpp.rej
patching file src/Plugins/Qt/qt_chooser_widget.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file src/Plugins/Qt/qt_chooser_widget.cpp.rej
patching file src/Plugins/Qt/qt_picture.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file src/Plugins/Qt/qt_picture.cpp.rej
patching file src/Plugins/Qt/qt_sys_utils.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/Plugins/Qt/qt_sys_utils.cpp.rej
patching file src/Plugins/Qt/qt_utilities.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
5 out of 5 hunks ignored -- saving rejects to file src/Plugins/Qt/qt_utilities.cpp.rej
patching file src/Plugins/Qt/qt_utilities.hpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/Plugins/Qt/qt_utilities.hpp.rej
The next patch would create the file src/Plugins/Windows/iostream.cpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/args.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/cenv.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/config.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/convert.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/cstdio.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/cstdlib.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/encoding_errors.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/encoding_utf.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/filebuf.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/fstream.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/iostream.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/scoped_ptr.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/stackstring.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/system.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/texmacs_modifications.patch,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/utf.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/utf8_codecvt.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/nowide/windows.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/Plugins/Windows/win-utf8-compat.hpp,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
patching file src/System/Boot/init_texmacs.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/System/Boot/init_texmacs.cpp.rej
patching file src/System/Files/file.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
10 out of 10 hunks ignored -- saving rejects to file src/System/Files/file.cpp.rej
patching file src/System/Files/tm_ostream.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
4 out of 4 hunks ignored -- saving rejects to file src/System/Files/tm_ostream.cpp.rej
patching file src/System/Misc/sys_utils.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file src/System/Misc/sys_utils.cpp.rej
patching file src/Texmacs/Texmacs/texmacs.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file src/Texmacs/Texmacs/texmacs.cpp.rej
patching file src/Typeset/Concat/concat_active.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/Typeset/Concat/concat_active.cpp.rej
==> ERREUR : Une erreur s’est produite dans prepare().
    Abandon…

**********************************************************
*                                                        *
*      The TeXmacs installer was not created...          *
*                                                        *
*            something went wrong :(                     *
**********************************************************

Press Enter to close this window...
"

best regards...

**Comment by slowphil** [comment]
Thanks for the report. As you can see from the logs, a patch failed. The reason is that it has been recently accepted in the trunk (on april 19) and thus it is no longer needed. I made the necessary change to the [PKGBUILD](https://github.com/slowphil/mingw-w64-texmacs/blob/master/PKGBUILD) yesterday. 
If you comment out that line and start again, it should work.

**Comment by Yibbou** [comment]
Thank you Philippe,
"prepare()" now work fine. The corresponding patches are ok.
News problems occur during the build process (see attached log file).

best regards

[mingw-w64-texmacs-svn11660+extras-1-i686-build.log](https://github.com/slowphil/texmacs-win-builder/files/3174251/mingw-w64-texmacs-svn11660%2Bextras-1-i686-build.log)
