### ISSUE TITLE
--force" option is not recognized by latest version of Pacman any more.

### ISSUE THREAD

**Issue by nerd-qp** [slowphil/texmacs-win-builder#5]
"--force" option is not recognized by latest version of Pacman any more. May need to update the .bat file.

**Comment by 326623** [comment]
"--force" option is not recognized by latest version of Pacman any more. May need to update the .bat file.

**Comment by slowphil** [comment]
Yes, I know. I [committed ](https://github.com/slowphil/texmacs-win-builder/commit/ddc64c3a9fc982e8596205bf7f99607a310c7068) a correction, and [released an updated installer](https://github.com/slowphil/texmacs-win-builder/releases/tag/0.94) to address this.
OTOH the executable installer still embeds the old pacman and the batch file first runs with that old pacman.  Have you experienced an error running the latest installer?

**Comment by nerd-qp** [comment]
I see. I used the link in README, which points to an old version (might need to update the README). I didn't encounter any problem with the latest installer. The process did take a while though, like an hour or two. Other than that, I have no issue.
Thanks a lot! Great stuff.

**Comment by slowphil** [comment]
I updated the README. Thanks for the feedback.
