### ISSUE TITLE
Packagers change from MSYS2 breaks the procedure

### ISSUE THREAD

**Issue by nerd-qp** [slowphil/texmacs-win-builder#6]
Some error occurred during the pacman update. Maybe we need to package newer version of MSYS2.

```
error: key "628F528CF3053E04" could not be looked up remotely
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```

Some references:

https://github.com/msys2/MSYS2-packages/issues/2058

https://www.msys2.org/news/#2020-06-29-new-packagers

**Comment by nerd-qp** [comment]
My current solution to this is:
1. Delete etc/pacman.d in this repo.
2. Find a workable msys2 environment and copy its etc/pacman.d over to this repo.

**Comment by slowphil** [comment]
Thanks for pointing the issue and providing a workaround/fix!
I hope I'll have time to look into it and hopefully fix the downloadable file in a couple of weeks. It's getting harder and harder though, with the deprecation of many packages (Qt4, Guile,) and the phasing out of MSYS2 32 bits (if I understand correctly)... Out of curiosity have you tried building the QT5 version?

**Comment by nerd-qp** [comment]
Unfortunately, my previous solution doesn't result in a successful pacman update. As a result, I have to migrate to an entirely new msys2 installation and execute the script there (manually).

Yes, it seems that qt4 and poppler-qt4 is not available from the official msys repo.

I encounter new errors:
'''
error: target not found: mingw-w64-i686-qt4
error: target not found: mingw-w64-i686-poppler-qt4
'''

I have successfully compiled with QT5 couple months back. If my memory serves me well, there is no hiccup once I have installed the qt5-static. I will try to find time to compile TeXmacs with QT5 and report back here.

**Comment by slowphil** [comment]
>  I have to migrate to an entirely new msys2 installation and execute the script there (manually).

Right, that's what I'm envisioning at the moment: repack the current MSYS2 installer such that it autostarts the build as it was previously. I'll tinker with that a soon as I can. 

> I have successfully compiled with QT5 couple months back. If my memory serves me well, there is no hiccup once I have installed the qt5-static. I will try to find time to compile TeXmacs with QT5 and report back here.

Good to know. Thanks.

**Comment by slowphil** [comment]
Fixed (for me, at least) in the [latest release](https://github.com/slowphil/texmacs-win-builder/releases/latest). 

If it works for you too, please close the issue.

**Comment by nerd-qp** [comment]
I can confirm a successful compilation from my end. Thanks :)
